/**
 * Pure markdown anchor/section utilities for Obsidian-style content.
 *
 * All functions take plain `content` strings — no filesystem access, no React.
 * Node-testable and safe to import in any context.
 */

// ─── Block ID matching ────────────────────────────────────────────────────────

/** Regex that matches a trailing Obsidian block marker: ` ^id` or `^id` at end of line. */
const BLOCK_MARKER_RE = /\^([A-Za-z0-9_-]+)\s*$/;

/**
 * Find the first line in `content` whose Obsidian block marker matches `id`.
 *
 * - `id` may be passed with or without a leading `^`.
 * - An own-line marker (the trimmed line is exactly `^id`) returns the text
 *   of the PRECEDING non-blank line (Obsidian's own-line rule).
 * - The ` ^id` suffix is stripped from the returned `text`.
 * - Returns null when not found or when content is empty.
 */
export function findBlockById(
  content: string,
  id: string,
): { line: number; text: string } | null {
  if (!content) return null;

  // Normalise: strip optional leading caret from the caller-supplied id.
  const bareId = id.startsWith("^") ? id.slice(1) : id;
  if (!bareId) return null;

  // Split on both LF and CRLF but preserve the original line endings stripped.
  const lines = content.split(/\r?\n/);

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    const match = BLOCK_MARKER_RE.exec(line);
    if (!match) continue;
    if (match[1] !== bareId) continue;

    // Determine line number (1-based).
    const lineNumber = i + 1;

    // Check if this is an own-line marker (trimmed line is exactly `^id`).
    const trimmed = line.trim();
    if (trimmed === `^${bareId}`) {
      // Find the preceding non-blank line.
      for (let j = i - 1; j >= 0; j--) {
        const prev = lines[j].trim();
        if (prev) {
          return { line: j + 1, text: lines[j].replace(/\r$/, "").trim() };
        }
      }
      // No preceding non-blank line — no match.
      return null;
    }

    // Inline marker — strip the ` ^id` suffix.
    const text = line.replace(/\r$/, "").replace(/\s*\^[A-Za-z0-9_-]+\s*$/, "").trim();
    return { line: lineNumber, text };
  }

  return null;
}

// ─── Heading slug ─────────────────────────────────────────────────────────────

/**
 * Convert a heading text to a slug that matches the DOM id generated by the
 * heading renderer (CopyHeadingLink / textToId).
 *
 * Steps: trim → lowercase → replace every run of non-alphanumeric chars with
 * a single hyphen → trim leading/trailing hyphens.
 *
 * This is the SINGLE source of truth for heading slug generation.  The
 * heading renderer imports and calls this function so that WikiLink scroll
 * targets always match the DOM ids.
 *
 * Note: underscores are treated as separators (converted to `-`), unlike the
 * old GitHub-style slug that kept `\w` chars (including `_`).
 */
export function slugifyHeading(text: string): string {
  return text
    .trim()
    .toLowerCase()
    // Replace every run of characters that are not a-z or 0-9 with a hyphen.
    .replace(/[^a-z0-9]+/g, "-")
    // Trim leading/trailing hyphens.
    .replace(/^-+|-+$/g, "");
}

// ─── Fence mask ───────────────────────────────────────────────────────────────

/**
 * Build a boolean mask over `lines` where `true` means the line is inside a
 * fenced code block (``` or ~~~).  The fence-open line itself is marked true
 * (it is not a heading), as is the fence-close line.
 */
function buildFenceMask(lines: string[]): boolean[] {
  const mask: boolean[] = new Array(lines.length).fill(false);
  let inFence = false;
  let fenceChar = "";

  for (let i = 0; i < lines.length; i++) {
    const stripped = lines[i].replace(/\r$/, "");
    const backtickFence = stripped.match(/^(`{3,})/);
    const tildeFence = stripped.match(/^(~{3,})/);

    if (!inFence) {
      if (backtickFence) {
        inFence = true;
        fenceChar = "`";
        mask[i] = true;
      } else if (tildeFence) {
        inFence = true;
        fenceChar = "~";
        mask[i] = true;
      }
    } else {
      mask[i] = true;
      const closingChar = fenceChar === "`" ? /^`{3,}\s*$/ : /^~{3,}\s*$/;
      if (closingChar.test(stripped)) {
        inFence = false;
        fenceChar = "";
      }
    }
  }

  return mask;
}

// ─── Heading enumeration ──────────────────────────────────────────────────────

const HEADING_RE = /^(#{1,6})\s+(.+)/;

/** Extract heading text from a line, or null if it's not a heading. */
function parseHeadingLine(
  line: string,
): { level: number; text: string } | null {
  const m = HEADING_RE.exec(line.replace(/\r$/, ""));
  if (!m) return null;
  return { level: m[1].length, text: m[2].trim() };
}

/**
 * Return the text of every ATX heading (`#`..`######`) in `content`,
 * excluding headings inside fenced code blocks.
 */
export function headingTexts(content: string): string[] {
  const lines = content.split(/\r?\n/);
  const mask = buildFenceMask(lines);
  const texts: string[] = [];
  for (let i = 0; i < lines.length; i++) {
    if (mask[i]) continue;
    const h = parseHeadingLine(lines[i]);
    if (h) texts.push(h.text);
  }
  return texts;
}

/**
 * Return the slug of every ATX heading in `content`,
 * excluding headings inside fenced code blocks.
 */
export function headingSlugs(content: string): string[] {
  return headingTexts(content).map(slugifyHeading);
}

// ─── validateAnchor ──────────────────────────────────────────────────────────

export interface AnchorValidation {
  kind: "none" | "block" | "heading";
  valid: boolean;
  value: string;
}

/**
 * Validate an anchor string against the given content.
 *
 * - Empty anchor → `{ kind: "none", valid: true, value: "" }`.
 * - Leading `^` → block anchor: valid when `findBlockById` finds it.
 * - Else → heading anchor: valid when any heading matches by case-insensitive
 *   text OR by slug.
 */
export function validateAnchor(
  content: string,
  anchor: string,
): AnchorValidation {
  if (!anchor) return { kind: "none", valid: true, value: "" };

  if (anchor.startsWith("^")) {
    const id = anchor.slice(1);
    const found = findBlockById(content, id);
    return { kind: "block", valid: found !== null, value: id };
  }

  // Heading anchor: match by case-insensitive text or by slug.
  const anchorLower = anchor.toLowerCase();
  const anchorSlug = slugifyHeading(anchor);
  const texts = headingTexts(content);
  const valid = texts.some(
    (t) =>
      t.toLowerCase() === anchorLower || slugifyHeading(t) === anchorSlug,
  );

  return { kind: "heading", valid, value: anchor };
}

// ─── extractSection ───────────────────────────────────────────────────────────

/**
 * Extract a content section identified by `anchor`.
 *
 * - `anchor === ""` → returns the whole content.
 * - `isBlock === true` → returns the block's line text via `findBlockById`.
 * - Else → heading mode: finds the matched heading line and returns it plus
 *   everything up to (not including) the next heading of equal-or-higher level.
 * - Missing anchor → `""`.
 * - CRLF-safe.
 */
export function extractSection(
  content: string,
  anchor: string,
  isBlock: boolean,
): string {
  if (anchor === "") return content;

  if (isBlock) {
    const found = findBlockById(content, anchor);
    return found ? found.text : "";
  }

  // Heading mode.
  const lines = content.split(/\r?\n/);
  const mask = buildFenceMask(lines);
  const anchorLower = anchor.toLowerCase();
  const anchorSlug = slugifyHeading(anchor);

  // Find the matching heading line index.
  let matchIndex = -1;
  let matchLevel = 0;

  for (let i = 0; i < lines.length; i++) {
    if (mask[i]) continue;
    const h = parseHeadingLine(lines[i]);
    if (!h) continue;
    if (
      h.text.toLowerCase() === anchorLower ||
      slugifyHeading(h.text) === anchorSlug
    ) {
      matchIndex = i;
      matchLevel = h.level;
      break;
    }
  }

  if (matchIndex === -1) return "";

  // Collect lines from matchIndex until we hit a heading of <= matchLevel.
  const result: string[] = [];
  for (let i = matchIndex; i < lines.length; i++) {
    if (i !== matchIndex) {
      // Check if this line is a heading of equal or higher level (lower number).
      if (!mask[i]) {
        const h = parseHeadingLine(lines[i]);
        if (h && h.level <= matchLevel) break;
      }
    }
    result.push(lines[i].replace(/\r$/, ""));
  }

  return result.join("\n");
}
